//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace BahaTurret
{
	public static class BDGUIUtils
	{
		public static Texture2D pixel;

		public static void DrawTextureOnWorldPos(Vector3 worldPos, Texture texture, Vector2 size, float wobble)
		{
			Vector3 screenPos = FlightCamera.fetch.mainCamera.WorldToViewportPoint(worldPos);
			float xPos = screenPos.x*Screen.width-(0.5f*size.x);
			float yPos = (1-screenPos.y)*Screen.height-(0.5f*size.y);
			if(wobble > 0)
			{
				xPos += UnityEngine.Random.Range(-wobble/2, wobble/2);
				yPos += UnityEngine.Random.Range(-wobble/2, wobble/2);
			}
			Rect iconRect = new Rect(xPos, yPos, size.x, size.y);
			float cameraAngle = Vector3.Angle(FlightCamera.fetch.GetCameraTransform().forward, worldPos-FlightCamera.fetch.mainCamera.transform.position);
			if(cameraAngle<90) GUI.DrawTexture(iconRect, texture);
		}

		public static void DrawRectangle(Rect rect, Color color)
		{
			if(pixel == null)
			{
				pixel = new Texture2D(1,1);
			}

			Color originalColor = GUI.color;
			GUI.color = color;
			GUI.DrawTexture(rect, pixel);
			GUI.color = originalColor;
		}
	}
}

