//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace BahaTurret
{
	public static class BDGUIUtils
	{
		public static Texture2D pixel;

		public static void DrawTextureOnWorldPos(Vector3 worldPos, Texture texture, Vector2 size, float wobble)
		{
			Vector3 screenPos = FlightCamera.fetch.mainCamera.WorldToViewportPoint(worldPos);
			float xPos = screenPos.x*Screen.width-(0.5f*size.x);
			float yPos = (1-screenPos.y)*Screen.height-(0.5f*size.y);
			if(wobble > 0)
			{
				xPos += UnityEngine.Random.Range(-wobble/2, wobble/2);
				yPos += UnityEngine.Random.Range(-wobble/2, wobble/2);
			}
			Rect iconRect = new Rect(xPos, yPos, size.x, size.y);
			float cameraAngle = Vector3.Angle(FlightCamera.fetch.GetCameraTransform().forward, worldPos-FlightCamera.fetch.mainCamera.transform.position);
			if(cameraAngle<90) GUI.DrawTexture(iconRect, texture);
		}

		public static void DrawLineBetweenWorldPositions(Vector3 worldPosA, Vector3 worldPosB, float width, Color color)
		{
			Vector3 screenPosA = FlightCamera.fetch.mainCamera.WorldToViewportPoint(worldPosA);
			screenPosA.x = screenPosA.x*Screen.width;
			screenPosA.y = (1-screenPosA.y)*Screen.height;
			Vector3 screenPosB = FlightCamera.fetch.mainCamera.WorldToViewportPoint(worldPosB);
			screenPosB.x = screenPosB.x*Screen.width;
			screenPosB.y = (1-screenPosB.y)*Screen.height;

			if(screenPosA.z < 0 && screenPosB.z < 0) return;
			screenPosA.z = screenPosB.z = 0;

			float angle = Vector2.Angle(Vector3.up, screenPosB - screenPosA);
			if(screenPosB.x < screenPosA.x)
			{
				angle = -angle;
			}

			Vector2 vector = screenPosB - screenPosA;
			float length = vector.magnitude;

			Rect upRect = new Rect(screenPosA.x - (width / 2), screenPosA.y-length, width, length);

			GUIUtility.RotateAroundPivot(-angle+180, screenPosA);
			DrawRectangle(upRect, color);
			GUI.matrix = Matrix4x4.identity;
		}

		public static void DrawRectangle(Rect rect, Color color)
		{
			if(pixel == null)
			{
				pixel = new Texture2D(1,1);
			}

			Color originalColor = GUI.color;
			GUI.color = color;
			GUI.DrawTexture(rect, pixel);
			GUI.color = originalColor;
		}

		public static void UseMouseEventInRect(Rect rect)
		{
			if(Misc.MouseIsInRect(rect) && Event.current.isMouse && (Event.current.type == EventType.MouseDown || Event.current.type == EventType.MouseUp))
			{
				Event.current.Use();
			}
		}
	}
}

