//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace BahaTurret
{
	public interface IBDWeapon 
	{
		WeaponClasses GetWeaponClass();
		string GetShortName();
		string GetSubLabel();
		Part GetPart();
	}

	public enum WeaponClasses{Missile, Bomb, Gun, Rocket, DefenseLaser}
}

