//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;

namespace BahaTurret
{
	public class TGPCameraEffects : MonoBehaviour 
	{
		public static Material grayscaleMaterial;
		
		public Texture  textureRamp;
		public float    rampOffset;

		Color origAmbientColor;

		void Awake()
		{
			if(!grayscaleMaterial)
			{
				grayscaleMaterial = new Material(BDAShaderLoader.LoadManifestShader("BahaTurret.GrayscaleEffectShader.shader"));
				grayscaleMaterial.SetTexture("_RampTex", textureRamp);
				grayscaleMaterial.SetFloat("_RampOffset", rampOffset);
			}
		}
		

		void OnPreRender()
		{
			if(ModuleTargetingCamera.activeCam.nvMode)
			{
				origAmbientColor = RenderSettings.ambientLight;
				RenderSettings.ambientLight = new Color(1,1,1,1);
			}
		}

		void OnRenderImage (RenderTexture source, RenderTexture destination) 
		{
			if(BDArmorySettings.BW_TARGET_CAM || TargetingCamera.Instance.nvMode)
			{
				Graphics.Blit (source, destination, grayscaleMaterial); //apply grayscale
			}
		}

		void OnPostRender()
		{
			if(ModuleTargetingCamera.activeCam.nvMode)
			{
				RenderSettings.ambientLight = origAmbientColor;
			}
		}
	}
}

