//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace BahaTurret
{
	public class CameraBulletRenderer : MonoBehaviour
	{
		public float resizeFactor = 1;
		Camera cam;

		void Awake()
		{
			cam = GetComponent<Camera>();
		}

		void OnPreRender()
		{
			if(ModuleWeapon.bulletPool)
			{
				for(int i = 0; i < ModuleWeapon.bulletPool.size; i++)
				{
					if(ModuleWeapon.bulletPool.GetPooledObject(i).activeInHierarchy)
					{
						PooledBullet pBullet = ModuleWeapon.bulletPool.GetPooledObject(i).GetComponent<PooledBullet>();
						pBullet.UpdateWidth(cam, resizeFactor);
					}
		
				}
			}
		}
	}
}

